### ISSUE TITLE
25 RC returned from certain projects when trying to add feature to liberty fails install

### ISSUE THREAD

**Issue by scottdickerson** [OpenLiberty/ci.gradle#326]
classpath 'net.wasdev.wlp.gradle.plugins:liberty-gradle-plugin:2.6.3'

Version
```
liberty {
    install {
        runtimeUrl = "http://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile7/19.0.0.7/wlp-webProfile7-19.0.0.7.zip"
    }
    // Install all requested liberty features
    server {
        configFile = file('src/main/liberty/config/server.xml')
        features {
            name = ['servlet-4.0']
            acceptLicense = true
        }
    }
    packageLiberty {
        archive = packageFile
        include = packagingType
    }
}
```

```
* What went wrong:
Execution failed for task ':installFeature'.
> CWWKM2002E: Failed to invoke [/Users/scottsd/Documents/GitHub/analytics-service-api/com.ibm.internal.rest.meta/build/wlp/bin/installUtility, install, --acceptLicense, servlet-4.0]. RC= 25 but expected=[0, 22].

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':installFeature'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
```

**Comment by cherylking** [comment]
Can you provide the build.gradle file and the referenced server.xml file? Since you are specifying a server.xml file, I would not expect the need to specify the servlet-4.0 feature in the build.gradle file.

**Comment by cherylking** [comment]
@scottdickerson Since this is nearly a year old, I presume you got past your issue and this can be closed?

**Comment by scottdickerson** [comment]
Yes thanks
