### ISSUE TITLE
Dev Mode: Add integration tests

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/ci.gradle#355]
Add gradle equivalents of dev mode integration tests https://github.com/OpenLiberty/ci.maven/tree/master/liberty-maven-plugin/src/it/dev-it

**Comment by ericglau** [comment]
WIP tests: https://github.com/ericglau/ci.gradle/tree/devBasicTest. Windows tests are failing, possibly due to #397 and #402

**Comment by ericglau** [comment]
WIndows tests fail https://ci.appveyor.com/project/ericglau/ci-gradle/builds/30241919/job/694smkqfjqb8rat0?fullLog=true 
```
io.openliberty.tools.gradle.DevTest > classMethod FAILED
    java.io.IOException: Unable to delete file: build\testBuilds\dev-test\basic-dev-project\output.log
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2400)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617)
        at org.apache.commons.io.FileUtils$deleteDirectory$2.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at io.openliberty.tools.gradle.DevTest.cleanUpAfterClass(DevTest.groovy:155)
        at io.openliberty.tools.gradle.DevTest.cleanUpAfterClass(DevTest.groovy:148)
```

**Comment by ericglau** [comment]
https://github.com/ericglau/ci.gradle/tree/devTests

**Comment by ericglau** [comment]
Above tests are failing on Windows because Appveyor runs `gradle clean` several times, and it fails after the first time because `gradle clean` is `Unable to delete file: C:\projects\ci-gradle\build\testBuilds\dev-test\basic-dev-project1580327993999\build\wlp\lib\com.ibm.ws.install_1.0.36.jar`

For now this is blocked by https://github.com/OpenLiberty/ci.gradle/issues/402

**Comment by ericglau** [comment]
Also, add a test for updating server.xml so that it installs a feature while dev mode is running
