### ISSUE TITLE
Dev mode hangs if server restart failed

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/ci.gradle#392]
To reproduce:
1. Use the `start` directory of this branch: https://github.com/ericglau/guide-gradle-intro/tree/testDevMode 
2. Start dev mode with `gradlew libertyDev`
3. Add the following in `build.gradle` to cause the server to restart and force it to fail due to out of memory:
```
afterEvaluate {
    ext {
        liberty.server.jvmOptions=['-Xms1m','-Xmx2m']
    }
}
```
4. The following is printed, after which dev mode hangs without responding to further changes (except it still allows running tests with Enter, but they will also fail because there is no server running).
```
CWWKM2001I: Invoke command is ["C:\Users\Eric\git\guide-gradle-intro\start\build\wlp\bin\server.bat", debug, GradleSampleServer].
Listening for transport dt_socket at address: 7777
Launching GradleSampleServer (Open Liberty 19.0.0.12/wlp-1.0.35.cl191220191120-0300) on OpenJDK 64-Bit Server VM, version 1.8.0_232-b09 (en_CA)
Unable to locate configured delegate: interface com.ibm.wsspi.logprovider.TrService, java.lang.OutOfMemoryError: Java heap space
CWWKE0005E: The runtime environment could not be launched.
CWWKE0018E: An exception occurred while launching the runtime environment: java.lang.NullPointerException: LogProviderConfig must provide a TrService delegate
com.ibm.ws.kernel.boot.LaunchException: Caught unexpected exception java.lang.NullPointerException: LogProviderConfig must provide a TrService delegate
        at com.ibm.ws.kernel.boot.internal.KernelBootstrap.rethrowException(KernelBootstrap.java:662)
        at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:219)
        at com.ibm.ws.kernel.boot.Launcher.handleActions(Launcher.java:241)
        at com.ibm.ws.kernel.boot.Launcher.createPlatform(Launcher.java:117)
        at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:59)
        at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:35)
Caused by: java.lang.NullPointerException: LogProviderConfig must provide a TrService delegate
        at com.ibm.websphere.ras.TrConfigurator.init(TrConfigurator.java:86)
        at com.ibm.ws.logging.internal.impl.LogProviderImpl.configure(LogProviderImpl.java:33)
        at com.ibm.ws.kernel.launch.internal.LauncherDelegateImpl.getLogProviderImpl(LauncherDelegateImpl.java:195)
        at com.ibm.ws.kernel.launch.internal.LauncherDelegateImpl.launchFramework(LauncherDelegateImpl.java:91)
        at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:213)
        ... 4 more
Exception in thread "Thread-98" CWWKM2002E: Failed to invoke ["C:\Users\Eric\git\guide-gradle-intro\start\build\wlp\bin\server.bat", debug, GradleSampleServer]. RC= 24 but expected=[0].
        at io.openliberty.tools.ant.AbstractTask.checkReturnCode(AbstractTask.java:216)
        at io.openliberty.tools.ant.ServerTask.doDebug(ServerTask.java:442)
        at io.openliberty.tools.ant.ServerTask.execute(ServerTask.java:171)
        at io.openliberty.tools.common.plugins.util.DevUtil$1.run(DevUtil.java:466)
        at java.lang.Thread.run(Thread.java:748)

> Task :libertyDev
An error occurred while starting the server: CWWKM2002E: Failed to invoke ["C:\Users\Eric\git\guide-gradle-intro\start\build\wlp\bin\server.bat", debug, GradleSampleServer]. RC= 24 but expected=[0].
CWWKM2002E: Failed to invoke ["C:\Users\Eric\git\guide-gradle-intro\start\build\wlp\bin\server.bat", debug, GradleSampleServer]. RC= 24 but expected=[0].
        at io.openliberty.tools.ant.AbstractTask.checkReturnCode(AbstractTask.java:216)
        at io.openliberty.tools.ant.ServerTask.doDebug(ServerTask.java:442)
        at io.openliberty.tools.ant.ServerTask.execute(ServerTask.java:171)
        at io.openliberty.tools.common.plugins.util.DevUtil$1.run(DevUtil.java:466)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by ericglau** [comment]
Dev mode should exit in this case, since the server is no longer running and the user should resolve the issue before running it again.

**Comment by rzgry** [comment]
So the serverTask is executed but it seems like no error is thrown since it does not reach the catch statement here https://github.com/OpenLiberty/ci.common/blob/c9fb4e015b84a7b171953d0a8c4c922a5212abd7/src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java#L478. Seems like the serverTask is either hanging or not throwing an exception for some reason. Closing this issue for now as it will take more time to investigate and it does not seem like a big issue as users can just exit and restart dev-mode.
