### ISSUE TITLE
Windows Appveyor tests failures with dev mode

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/ci.gradle#439]
https://ci.appveyor.com/project/wasdevb1/ci-gradle/builds/30805229/job/ikf9kbkcuiuryeda
Environment: jdk=C:\Program Files\Java\jdk1.8.0\bin:, RUNTIME=ol, RUNTIME_VERSION=20.0.0.1

Log is attached: [log (1).txt](https://github.com/OpenLiberty/ci.gradle/files/4221739/log.1.txt)

Tests only fail on Windows. Happens on all Liberty versions. Error is:
java.io.IOException: The pipe is being closed

```
io.openliberty.tools.gradle.PollingDevTest STANDARD_OUT
    Starting dev mode with polling...
    Running command: C:\projects\ci-gradle\gradlew.bat libertyDev --polling
    Dev mode output: 
    FAILURE: Build failed with an exception.
    * What w2 actionable tasks: 2 executed
    > Task :libertyDev FAILED
    1 actionable task: 1 executed
    set, it must point to a directory that contains lib/ws-launch.jar.
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    * Get more help at https://help.gradle.org
    BUILD FAILED in 9s
    FAILURE: Build failed with an exception.
    * What went wrong:
    Execution failed for task ':libertyDev'.
    > Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-5.1-bin.zip'.
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    * Get more help at https://help.gradle.org
    BUILD FAILED in 11s
io.openliberty.tools.gradle.PollingDevTest > classMethod FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertFalse(Assert.java:64)
        at org.junit.Assert.assertFalse(Assert.java:74)
        at org.junit.Assert$assertFalse$0.callStatic(Unknown Source)
        at io.openliberty.tools.gradle.DevTest.startProcess(DevTest.groovy:134)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1491)
        at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.callStatic(StaticMetaClassSite.java:64)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:196)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:216)
        at io.openliberty.tools.gradle.PollingDevTest.runDevModePolling(PollingDevTest.groovy:43)
        at io.openliberty.tools.gradle.PollingDevTest.setup(PollingDevTest.groovy:38)
io.openliberty.tools.gradle.PollingDevTest > classMethod FAILED
    java.io.IOException: The pipe is being closed
```

**Comment by TrevCraw** [comment]
No longer using Appveyor for dev mode automated tests.
