### ISSUE TITLE
user feature install fails with Gradle 7

### ISSUE THREAD

**Issue by jjiwooLim** [OpenLiberty/ci.gradle#667]
Running `gradle installFeature` to install user feature fails on Gradle 7.

Related Gradle issue:
https://github.com/gradle/gradle/issues/13122

Problem happens when we recompile Gradle using the ProjectBuilder API to fetch new features.json artifact (generated by prepareFeature) from the Mavenlocal repo. 

==Error log & stack trace==
* What went wrong:
Execution failed for task ':installFeature'.
> The settings are not yet available for build 'regFeature'.
...
Caused by: java.lang.IllegalStateException: The settings are not yet available for build 'regFeature'.
        at org.gradle.invocation.DefaultGradle.getSettings(DefaultGradle.java:207)
        at org.gradle.invocation.DefaultGradle_Decorated.getSettings(Unknown Source)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.ignoresSettingsRepositories(DefaultConfiguration.java:756)

**Comment by cherylking** [comment]
@jjiwooLim Any outlook on this one?
